bugfix/payout_bankwire_bug fixed
Mangopay/mangopay2-java-sdk pull request #246
Opened 2021-05-19 19:41 UTC by SoloJr

2021-05-20 08:07 UTC, fredericdelordm commented on src/test/java/com/mangopay/core/BaseTest.java
> +            ((PayOutPaymentDetailsBankWire) payOut.getMeanOfPaymentDetails()).setPayoutModeRequested(PayoutMode.STANDARD);
@SoloJr Does it take into account "INSTANT_PAYMENT" value for the PayoutModeRequested parameter ?

2021-05-20 08:07 UTC, fredericdelordm commented on src/main/java/com/mangopay/core/deserializer/PayOutDeserializer.java
> +                if (object.has("ModeApplied") && !object.get("ModeApplied").isJsonNull())
@SoloJr https://docs.mangopay.com/guide/instant-payment-payout

Do we take into account Status && FallbackReason ?

2021-05-20 08:08 UTC, fredericdelordm requested changes
Hello @SoloJr I have added some questions

2021-05-25 17:44 UTC, SoloJr commented on src/test/java/com/mangopay/core/BaseTest.java
> +            ((PayOutPaymentDetailsBankWire) payOut.getMeanOfPaymentDetails()).setPayoutModeRequested(PayoutMode.STANDARD);
@fredericdelordm yes it does, but I cannot test this case due to API limitations ("Payout author is not Kyc validated for InstantPayment")

2021-05-26 08:04 UTC, fredericdelordm approved these changes

2021-05-26 20:37 UTC, merged